global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docai-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # DocAI application metrics
  - job_name: 'docai'
    static_configs:
      - targets: ['docai:8090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # Nginx metrics (requires nginx-vts-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']